use_frameworks!

platform :ios, '10.0'

target 'MLTNumberScrollAnimatedView_Example' do
  pod 'MLTNumberScrollAnimatedView', :path => '../'

  target 'MLTNumberScrollAnimatedView_Tests' do
    inherit! :search_paths

    
  end
end
