use_frameworks!

platform :ios, '12.0'

target 'MLTNumberScrollAnimatedView_Example' do
  pod 'MLTNumberScrollAnimatedView', :path => '../'
  pod 'SnapKit'
  
  target 'MLTNumberScrollAnimatedView_Tests' do
    inherit! :search_paths

    
  end
end
